create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table user (id bigint not null, date_of_birh date, email varchar(255), gender integer, password_hash varchar(255), salt varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
